export const Config = {
    TOKEN_EXPIRY: 1, // minutes
    SESSION_MAX: 10,
    CURRENT_TAB: "CURRENT_TAB",
    LAST_ACTIVE_TAB: "LAST_ACTIVE_TAB",
    ACCESS_TOKEN: "ACCESS_TOKEN",
    REFRESH_TOKEN: "REFRESH_TOKEN",
    PUBLIC_KEY: "PUBLIC_KEY",
    PRIVATE_KEY: "PRIVATE_KEY",
};